name: Build and Release

on:
  push:
    branches: [ build ]

permissions:
  contents: write  # Needed for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for version calculation

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Calculate version
        id: version
        run: |
          # Get the current date and time
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%H%M%S')
          
          # Get the short commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Create version string: YYYYMMDD-HHMMSS-commit
          VERSION="${DATE}-${TIME}-${COMMIT_HASH}"
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Calculated version: $VERSION"

      - name: Create zip file
        run: |
          # Create zip file with calculated version
          zip -r "wosb-game-${{ env.VERSION }}.zip" dist/ -x "*.map" "*.d.ts"
          echo "Created zip file: wosb-game-${{ env.VERSION }}.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Release ${{ env.VERSION }}"
          files: |
            wosb-game-${{ env.VERSION }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}